(function ($) {
var $body = $('body');
var $page = $('.page');
var $detail = $('.detail');
var $theme = $('.theme-toggle');
var $button = $('.button');
var $bg = $('.bg');
var $window = $('.window');
var $bar = $('.bar');
var $abaMenu = $('.abaMenu');
var $status = $('.status');
var $a = $('a');
var $imagicine = $('.imagicine');
var $option = $('.option');
var $playall = $('.playall');
var $controls = $('.controls');
var $vsf = $('.colour');
var $procurar = $('.procurar');
var $faixas = $('.faixas');
var $faixa = $('.faixa');
var $time = $('.number');
var $session = $('.session');
var $detailcolor = $('.colour.details');
var $number = $('.time');
var $proguesso = $('.seek-bar .progress-bar');
var $play = $('.play');
var $next = $('.next');
var $prev = $('.prev');
var $errorspan = $('.errorUpdate .error span');
var $erroroptions = $('.errorUpdate .options');
var $errorUpdate = $('.errorUpdate');
var $geraltema = $('.geraltema');
var $span = $('.about .app-name span');
var $area = $('.window .content .area');
var $tenta = $('.window.about .content .area');
var $search = $('.search');
var $letras = $('.letras');
var $amusica = $('.amusica');
var $imc = $('.imc');
var $lyricscreen = $('.lyricscreen');
var $closebtn = $('.closebtn');
var $progress = $('.progress-bar');
var $letras = $('.letras');
var loadTheme = function () {
$page.attr('theme', localStorage.getItem('theme') || 'default');
$detail.attr('theme', localStorage.getItem('theme') || 'default');
$theme.attr('theme', localStorage.getItem('theme') || 'default');
$controls.attr('theme', localStorage.getItem('theme') || 'default');
$procurar.attr('theme', localStorage.getItem('theme') || 'default');
$button.attr('theme', localStorage.getItem('theme') || 'default');
$a.attr('theme', localStorage.getItem('theme') || 'default');
$errorUpdate.attr('theme', localStorage.getItem('theme') || 'default');
$area.attr('theme', localStorage.getItem('theme') || 'default');
$faixa.attr('theme', localStorage.getItem('theme') || 'default');
$imagicine.attr('theme', localStorage.getItem('theme') || 'default');
$option.attr('theme', localStorage.getItem('theme') || 'default');
$proguesso.attr('theme', localStorage.getItem('theme') || 'default');
$bar.attr('theme', localStorage.getItem('theme') || 'default');
$faixas.attr('theme', localStorage.getItem('theme') || 'default');
$number.attr('theme', localStorage.getItem('theme') || 'default');
$status.attr('theme', localStorage.getItem('theme') || 'default');
$vsf.attr('theme', localStorage.getItem('theme') || 'default');
$abaMenu.attr('theme', localStorage.getItem('theme') || 'default');
$span.attr('theme', localStorage.getItem('theme') || 'default');
$errorspan.attr('theme', localStorage.getItem('theme') || 'default');
$erroroptions.attr('theme', localStorage.getItem('theme') || 'default');
$geraltema.attr('theme', localStorage.getItem('theme') || 'default');
$window.attr('theme', localStorage.getItem('theme') || 'default');
$playall.attr('theme', localStorage.getItem('theme') || 'default');
$time.attr('theme', localStorage.getItem('theme') || 'default');
$play.attr('theme', localStorage.getItem('theme') || 'default');
$search.attr('theme', localStorage.getItem('theme') || 'default');
$letras.attr('theme', localStorage.getItem('theme') || 'default');
$next.attr('theme', localStorage.getItem('theme') || 'default');
$bg.attr('theme', localStorage.getItem('theme') || 'default');
$tenta.attr('theme', localStorage.getItem('theme') || 'default');
$prev.attr('theme', localStorage.getItem('theme') || 'default');
$session.attr('theme', localStorage.getItem('theme') || 'default');
$amusica.attr('theme', localStorage.getItem('theme') || 'default');
$detailcolor.attr('theme', localStorage.getItem('theme') || 'default');
$window.attr('theme', localStorage.getItem('theme') || 'default');
$imc.attr('theme', localStorage.getItem('theme') || 'default');
$lyricscreen.attr('theme', localStorage.getItem('theme') || 'default');
$closebtn.attr('theme', localStorage.getItem('theme') || 'default');
$progress.attr('theme', localStorage.getItem('theme') || 'default');
$lyricbody.attr('theme', localStorage.getItem('theme') || 'default');
$body.attr('theme', localStorage.getItem('theme') || 'default');
};
$('.theme-toggle').click(function () {
localStorage.setItem('theme', $(this).data('theme'));
loadTheme();
});
loadTheme();
} (jQuery));